variables:
  RELEASE: "25.08"

default:
  image: "freedesktopsdk/sdk:${RELEASE}"
  interruptible: true

stages:
  - build

.build_template:
  stage: build
  except:
  - master
  retry:
    max: 2
    when: runner_system_failure
  script:
  - meson setup _build-dir
  - meson dist -C _build-dir

build_x86_64:
  extends:
  - .build_template
  tags:
  - x86_64
  variables:
    ARCH: x86_64

build_i686:
  extends:
  - .build_template
  tags:
  - x86_64
  variables:
    ARCH: i686

build_aarch64:
  extends:
  - .build_template
  tags:
  - aarch64
  variables:
    ARCH: aarch64
