variables:
  BST_CACHE_SERVER_ADDRESS: 'cache.freedesktop-sdk.io'
  IMAGE_ID: '543571583e6271ede4c706aff60d389cf26a13e9'
  # Docker Images
  DOCKER_REGISTRY: "registry.gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images"

  XDG_CACHE_HOME: "${CI_PROJECT_DIR}/cache"

default:
  image: "${DOCKER_REGISTRY}/bst16:${IMAGE_ID}"
  interruptible: true

stages:
  - build

.build_template:
  stage: build
  script:
  - ulimit -n 1048576
  - |
    if [ -n "$BB_CAS_PUSH_CERT" ] && [ -n "$BB_CAS_PUSH_KEY" ]; then
      mkdir -p /etc/ssl/CAS
      echo "$BB_CAS_PUSH_CERT" > /etc/ssl/CAS/server.crt
      echo "$BB_CAS_PUSH_KEY" > /etc/ssl/CAS/server.key
    fi

  - |
    mkdir -p ~/.config
    cat > ~/.config/buildstream.conf << EOF
    # Get a lot of output in case of errors
    logging:
      error-lines: 80
    # Force higher parallelity
    build:
      max-jobs: $(( $(nproc) / 4 ))
    
    EOF

  - |
    {
    echo "projects:"
    echo "  freedesktop-sdk:"
    echo "    artifacts:"
    if [ -f "/cache-certificate/server.crt" ]; then
    echo "    - url: https://local-cas-server:1102"
    echo "      server-cert: /cache-certificate/server.crt"
    if [ -f "/etc/ssl/CAS/server.key" ]; then
    echo "      client-key: /etc/ssl/CAS/server.key"
    echo "      client-cert: /etc/ssl/CAS/server.crt"
    echo "      push: true"
    fi
    fi
    if [ -f "/etc/ssl/CAS/server.key" ]; then
    echo "    - url: https://${BST_CACHE_SERVER_ADDRESS}:11002"
    echo "      client-key: /etc/ssl/CAS/server.key"
    echo "      client-cert: /etc/ssl/CAS/server.crt"
    echo "      push: true"
    else
    echo "    - url: https://${BST_CACHE_SERVER_ADDRESS}:11001"
    fi
    } >> ~/.config/buildstream.conf
  - | 
    bst --colors -o arch ${ARCH} build shared-library-guard.bst

  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/cache/buildstream/logs

build_x86_64:
  extends:
  - .build_template
  tags:
  - x86_64
  variables:
    ARCH: x86_64

build_i686:
  extends:
  - .build_template
  tags:
  - x86_64
  variables:
    ARCH: i686

build_aarch64:
  extends:
  - .build_template
  tags:
  - aarch64
  variables:
    ARCH: aarch64
