name: shared-library-guard

element-path: elements
ref-storage: project.refs
fail-on-overlap: true

aliases:
  (@): freedesktop-sdk.bst:include/aliases.yml

(@): freedesktop-sdk.bst:include/mirrors.yml

variables:
  (@):
    - freedesktop-sdk.bst:include/arch.yml
    - freedesktop-sdk.bst:include/build-dirs.yml
    - freedesktop-sdk.bst:include/build-flags.yml
    - freedesktop-sdk.bst:include/strip.yml

  sysroot: /cross-installation
  tools: /cross

environment:
  (@): freedesktop-sdk.bst:include/environment.yml

split-rules:
  (@): freedesktop-sdk.bst:include/split-rules.yml

plugins:
  - origin: pip
    package-name: buildstream-external
    elements:
      collect_integration: 0
      collect_manifest: 0
      flatpak_image: 0
      flatpak_repo: 0
      tar_element: 0
      x86image: 0
      oci: 0
    sources:
      git_tag: 1

options:
  target_arch:
    type: arch
    description: Architecture
    variable: arch
    values:
      - arm
      - aarch64
      - i686
      - x86_64
      - powerpc64le

elements:
  cmake:
    (@): freedesktop-sdk.bst:include/cmake-conf.yml
  autotools:
    (@): freedesktop-sdk.bst:include/autotools-conf.yml
  meson:
    (@): freedesktop-sdk.bst:include/meson-conf.yml
  pip:
    (@): freedesktop-sdk.bst:include/pip.yml

sources:
  git_tag:
    (@): freedesktop-sdk.bst:include/git_tag-conf.yml
