name: shared-library-guard

min-version: 2.0

element-path: elements

fatal-warnings:
- overlaps

aliases:
  pypi: https://files.pythonhosted.org/packages/
  (@): freedesktop-sdk.bst:include/_private/aliases.yml

(@):
- freedesktop-sdk.bst:include/runtime.yml

variables:
  sysroot: /cross-installation
  tools: /cross

plugins:
- origin: junction
  junction: plugins/buildstream-plugins.bst
  elements:
  - meson
  sources:
  - patch

- origin: junction
  junction: plugins/bst-plugins-experimental.bst
  elements:
  - pyproject
  sources:
  - git_repo
  - pypi

options:
  arch:
    type: arch
    description: Architecture
    variable: arch
    values:
      - arm
      - aarch64
      - i686
      - x86_64
      - powerpc64le
